<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 8.5px; color: #111; margin: 28px 24px; background: #fff; }
        .center { text-align: center; }
        .logo { max-height: 64px; margin: 0 auto 8px; display: block; }
        .biz-name { font-size: 14px; font-weight: bold; margin-top: 4px; }
        .biz-line { font-size: 9.5px; line-height: 1.45; color: #222; }
        .divider { border: none; border-top: 1px solid #000; margin: 14px 0 12px; }
        .report-title { font-size: 14px; font-weight: bold; letter-spacing: 0.5px; margin: 0 0 6px; }
        .date-range { font-size: 9.5px; margin-bottom: 12px; }
        table.data { width: 100%; border-collapse: collapse; margin-top: 4px; }
        table.data th, table.data td { border: 1px solid #222; padding: 4px 5px; vertical-align: top; }
        table.data th { background: #000; color: #fff; font-size: 7.5px; font-weight: bold; }
        table.data td { font-size: 7.5px; }
        table.data tbody tr:nth-child(even) td { background: #f3f3f3; }
        .summary-wrap { margin-top: 16px; }
        .summary-title { font-size: 10px; font-weight: bold; margin-bottom: 6px; }
        table.summary { width: 100%; max-width: 480px; border-collapse: collapse; font-size: 9px; }
        table.summary td { border: 1px solid #222; padding: 5px 7px; }
        table.summary td.label { font-weight: bold; width: 50%; background: #fafafa; }
        table.summary td.val { text-align: right; }
        .footer { margin-top: 18px; text-align: center; font-size: 9px; line-height: 1.5; color: #222; }
        .footer-thanks { font-weight: bold; margin-bottom: 3px; }
    </style>
</head>
<body>
    @if (!empty($logoSrc))
        <div class="center"><img class="logo" src="{{ $logoSrc }}" alt="KOPHI KIKI"></div>
    @endif

    <div class="center">
        <div class="biz-name">KOPHI KIKI</div>
        <div class="biz-line"><strong>KIK-LIGIN KA SA SARAP</strong></div>
        <div class="biz-line">Tatsulok Night Market, Fil-Am Avenue in Barangay Fatima, General Santos City</div>
        <div class="biz-line">09920307525</div>
    </div>

    <hr class="divider">

    <div class="center report-title">{{ strtoupper($reportTitle) }}</div>
    <div class="center date-range">Date Range: {{ $summary['date_range_line'] ?? '' }}</div>

    <table class="data">
        <thead>
            <tr>
                @foreach ($headers as $label)
                    <th>{{ $label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach (array_keys($headers) as $key)
                        <td>{{ $row[$key] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}" style="text-align:center;padding:12px;">No records in this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary-wrap">
        <div class="summary-title">SUMMARY</div>
        <table class="summary">
            @if ($reportType === \App\Services\AdminReportExportService::TYPE_INVENTORY)
                <tr>
                    <td class="label">Total SKUs</td>
                    <td class="val">{{ $summary['total_skus'] ?? 0 }}</td>
                </tr>
                <tr>
                    <td class="label">Total units in stock</td>
                    <td class="val">{{ $summary['total_units'] ?? 0 }}</td>
                </tr>
            @else
                <tr>
                    <td class="label">Total Sales</td>
                    <td class="val">₱{{ number_format((float) ($summary['total_sales'] ?? 0), 2, '.', ',') }}</td>
                </tr>
                <tr>
                    <td class="label">Total Orders</td>
                    <td class="val">{{ $summary['total_orders'] ?? 0 }}</td>
                </tr>
                <tr>
                    <td class="label">Total Items Sold</td>
                    <td class="val">{{ $summary['total_items'] ?? 0 }}</td>
                </tr>
                <tr>
                    <td class="label">Total Payments</td>
                    <td class="val">₱{{ number_format((float) ($summary['total_payments'] ?? 0), 2, '.', ',') }}</td>
                </tr>
                <tr>
                    <td class="label">Total Change</td>
                    <td class="val">₱{{ number_format((float) ($summary['total_change'] ?? 0), 2, '.', ',') }}</td>
                </tr>
            @endif
            <tr>
                <td class="label">Report Generated By</td>
                <td class="val">{{ $generatedBy }}</td>
            </tr>
            <tr>
                <td class="label">Generated Date &amp; Time</td>
                <td class="val">{{ $generatedAt }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <div class="footer-thanks">Thank you!</div>
        <div>This is a system generated report.</div>
    </div>
</body>
</html>
